In [1]:
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy')

In [2]:

scalar = StandardScaler()
insta_data = pd.read_csv('C:\\Users\\ankur\\Downloads\\train.csv')
insta_data.describe()

,profile pic,nums/length username,fullname words,nums/length fullname,name==username,description length,external URL,private,#posts,#followers,#follows,fake
count,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,5.760000e+02,576.000000,576.000000
mean,0.701389,0.163837,1.460069,0.036094,0.034722,22.623264,0.567708,0.381944,107.489583,8.530724e+04,508.381944,0.500000
std,0.458047,0.214096,1.052601,0.125121,0.183234,37.702987,0.495825,0.486285,402.034431,9.101485e+05,917.981239,0.500435
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.900000e+01,57.500000,0.000000
50%,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,9.000000,1.505000e+02,229.500000,0.500000
75%,1.000000,0.310000,2.000000,0.000000,0.000000,34.000000,1.000000,1.000000,81.500000,7.160000e+02,589.500000,1.000000
max,1.000000,0.920000,12.000000,1.000000,1.000000,150.000000,1.000000,1.000000,7389.000000,1.533854e+07,7500.000000,1.000000

In [3]:
lr_model = LogisticRegression(max_iter = 1000)
x_train = insta_data.drop(columns = ['fake'])
x_train1 = np.array(x_train)
x_train1

array([[1.00e+00, 2.70e-01, 0.00e+00, ..., 3.20e+01, 1.00e+03, 9.55e+02],
       [1.00e+00, 0.00e+00, 2.00e+00, ..., 2.86e+02, 2.74e+03, 5.33e+02],
       [1.00e+00, 1.00e-01, 2.00e+00, ..., 1.30e+01, 1.59e+02, 9.80e+01],
       ...,
       [1.00e+00, 5.70e-01, 2.00e+00, ..., 4.00e+00, 9.60e+01, 3.39e+02],
       [1.00e+00, 5.70e-01, 1.00e+00, ..., 0.00e+00, 5.70e+01, 7.30e+01],
       [1.00e+00, 2.70e-01, 1.00e+00, ..., 2.00e+00, 1.50e+02, 4.87e+02]])

In [4]:
y_train = insta_data['fake']
y_train1 = np.array(y_train)
y_train1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1], dtype=int64)

In [5]:

x_test = pd.read_csv('C:\\Users\\ankur\\Desktop\\test.csv')
x_test

,profile pic,nums/length username,fullname words,nums/length fullname,name==username,description length,external URL,private,#posts,#followers,#follows,fake
0,1,0.33,1,0.33,1,30,0,1,35,488,604,0
1,1,0.00,5,0.00,0,64,0,1,3,35,6,0
2,1,0.00,2,0.00,0,82,0,1,319,328,668,0
3,1,0.00,1,0.00,0,143,0,1,273,14890,7369,0
4,1,0.50,1,0.00,0,76,0,1,6,225,356,0
...,...,...,...,...,...,...,...,...,...,...,...,...
116,1,0.40,1,0.00,0,0,1,0,4,150,164,1
117,1,0.00,2,0.00,0,0,1,0,3,833,3572,1
118,0,0.17,1,0.00,0,0,1,0,1,219,1695,1
119,1,0.44,1,0.00,0,0,1,0,3,39,68,1
120,1,0.42,1,0.00,0,0,0,0,12,12,11111,1

In [6]:
x_test1 = x_test.drop(columns = ['fake'])
x_test1
y_test1 = x_test['fake']
y_test2 = np.array(y_test1)

In [7]:
x_test2 = np.array(x_test1)
x_test2

array([[1.0000e+00, 3.3000e-01, 1.0000e+00, ..., 3.5000e+01, 4.8800e+02,
        6.0400e+02],
       [1.0000e+00, 0.0000e+00, 5.0000e+00, ..., 3.0000e+00, 3.5000e+01,
        6.0000e+00],
       [1.0000e+00, 0.0000e+00, 2.0000e+00, ..., 3.1900e+02, 3.2800e+02,
        6.6800e+02],
       ...,
       [0.0000e+00, 1.7000e-01, 1.0000e+00, ..., 1.0000e+00, 2.1900e+02,
        1.6950e+03],
       [1.0000e+00, 4.4000e-01, 1.0000e+00, ..., 3.0000e+00, 3.9000e+01,
        6.8000e+01],
       [1.0000e+00, 4.2000e-01, 1.0000e+00, ..., 1.2000e+01, 1.2000e+01,
        1.1111e+04]])

In [8]:
lr_model.fit(x_train1,y_train1)
y_pred = lr_model.predict(x_test2)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [9]:
classifier.fit(x_train1,y_train1)
classifier.predict(x_test2)
classifier.score(x_test2,y_test2)

0.9669421487603306

In [ ]:
predicted_value = []
testv = []
for i in y_pred:
    predicted_value.append(np.argmax(i))
    
for i in y_test2:
    testv.append(np.argmax(i))
    
print(classification_report(testv, predicted_value))
plt.figure(figsize = (10,10))
con_matrix = confusion_matrix(testv,predicted_value)
sns.heatmap(con_matrix,annot=True)